Arturo
ksquareincmx/poc-chef-client pull request #11
Opened 2019-01-17 17:55 UTC by CanKer

2019-01-17 18:04 UTC, mishelashala requested changes

2019-01-17 18:04 UTC, mishelashala commented on src/components/Order.tsx
> +  // const DivOrder = styled.div({
delete commented/unused code

2019-01-17 18:04 UTC, mishelashala commented on src/components/event/Create.tsx
> +    const validation =
extract logic into a function

2019-01-17 18:04 UTC, mishelashala commented on src/components/event/Create.tsx
> +  public eventName = React.createRef<HTMLInputElement>();
why do yo need the refs?

2019-01-17 18:04 UTC, mishelashala commented on src/components/orders/DataOrder
> +import React from "react";
data order has no extension file

2019-01-17 19:36 UTC, CanKer commented on src/components/orders/DataOrder
> +import React from "react";
Yeah, I'll untrack

2019-01-17 19:36 UTC, CanKer commented on src/components/Order.tsx
> +  // const DivOrder = styled.div({
untracking

2019-01-17 19:37 UTC, CanKer commented on src/components/event/Create.tsx
> +  public eventName = React.createRef<HTMLInputElement>();
for the data in the form

2019-01-18 16:37 UTC, mishelashala approved these changes

2019-01-18 21:42 UTC, merged