Load data in event form show notifications
ksquareincmx/poc-chef-client pull request #131
Opened 2019-04-29 22:10 UTC by Andreslw

Load data in event-form
Update event info
add notification when an event is created or updated,
add notification when are fields are empty, before save.

2019-04-29 23:01 UTC, mishelashala requested changes

2019-04-29 23:01 UTC, mishelashala commented on src/partner/modules/ui/Modal/Notification.tsx
> +      <ButtonClose onClick={() => props.close()}>
```suggestion
      <ButtonClose onClick={props.close}>
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/services/EventService.ts
> +      console.error(err);
delete logs

2019-04-29 23:01 UTC, mishelashala commented on src/partner/services/EventService.ts
> +      const eventId = event.id;
```suggestion
      const { id as eventId, ...eventEntity } = event;
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/services/EventService.ts
> +      delete event["id"]; //not allowed by the server
```suggestion
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/services/EventService.ts
> +      putConfig.body = JSON.stringify(EventMapper.toDTO(event));
```suggestion
      putConfig.body = JSON.stringify(EventMapper.toDTO(eventEntity));
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/services/EventService.ts
> +      if (data.statusCode === 201) {
use early return

```js
if (data.statusCode !== 200) {
  throw new Error("Error at updating event");
}

return data;
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/views/CreateEvent/CreateEvent.tsx
> +    let res;
use ternary instead

```js
let res = isEditing ? await eventService.putEvent({ ...state }) : await eventService.postEvent({ ...state })
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/views/CreateEvent/CreateEvent.tsx
> +      notificationContext.handleShowNotification(errors.join(", "));
keep consistency:

```suggestion
      return notificationContext.handleShowNotification(errors.join(", "));
```

2019-04-29 23:01 UTC, mishelashala commented on src/partner/views/CreateEvent/CreateEvent.tsx
> +      return;
```suggestion
```

2019-04-30 16:53 UTC, Andreslw commented on src/user/services/OrderService.tsx
> +      console.error(err);
omit this one

2019-04-30 17:47 UTC, mishelashala approved these changes

2019-04-30 19:06 UTC, merged