event is deleted after cancel it
ksquareincmx/poc-chef-client pull request #30
Opened 2019-02-26 22:41 UTC by Andreslw

2019-02-26 22:50 UTC, mishelashala requested changes

2019-02-26 22:50 UTC, mishelashala commented on src/partner/modules/EventList/EventListContainer.tsx
> +  handleCancelEvent: Function;
avoid using `Function`, if the function just takes any event a doesn't return anything use:

```ts
export interface IEventListContainerProps {
  handleCancelEvent: (e: any) => void;
}
```

else use a meaningful function signature

2019-02-26 22:50 UTC, mishelashala commented on src/partner/modules/EventList/EventList.tsx
> +  handleCancelEvent: Function;
avoid using `Function`, if the function just takes any event a doesn't return anything use:

```ts
export interface IEventListContainerProps {
  handleCancelEvent: (e: any) => void;
}
```

else use a meaningful function signature

2019-02-26 22:50 UTC, mishelashala commented on src/partner/modules/EventList/EventListItem.tsx
> +  handleCancelEvent: Function;
avoid using `Function`, if the function just takes any event a doesn't return anything use:

```ts
export interface IEventListContainerProps {
  handleCancelEvent: (e: any) => void;
}
```

else use a meaningful function signature

2019-02-26 23:19 UTC, mishelashala approved these changes

2019-02-27 15:51 UTC, mishelashala commented on src/partner/views/EventView.tsx
> +          }
why the curly braces?

2019-02-27 16:03 UTC, Andreslw commented on src/partner/views/EventView.tsx
> +          }
component was commented

2019-02-27 16:40 UTC, merged